version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: "mongo"
    restart: always
    env_file:
      - ./.env
    networks:
      - im-uber-net
    ports:
      - 27017:27017
    volumes:
      - ./.db_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  
  server:
    container_name: im-uber-server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./server/.env
    command: npm run start
    networks:
      - im-uber-net
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/app/src
    depends_on:
      - mongodb

  client:
    container_name: im-uber-client
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    command: npm run dev
    networks:
      - im-uber-net
    ports:
      - 8080:8080
    volumes:
      - ./client/src:/app/src
    depends_on:
      - server

networks:
  im-uber-net:
    driver: bridge
